export const SOC_REQ_TYPES = Object.freeze({

    CANVAS_UPDATE: 'CANVAS_UPDATE',
    CHAT: 'CHAT',
    WHO_AM_I: 'WHO_AM_I',
    CLEAR_CANVAS: 'CLEAR_CANVAS',
    START_GAME: 'START_GAME',
    GAME_STARTED: 'GAME_STARTED',
    GAME_STATE_UPDATE: 'GAME_STATE_UPDATE',
    GAME_OVER: 'GAME_OVER',
    ATTENDANCE: 'ATTENDANCE',
    GAME_STATE: 'GAME_STATE',
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    UNDO_CANVAS:'UNDO_CANVAS',
    CHOOSE_WORD:'CHOOSE_WORD',
    CHOSEN_WORD:'CHOSEN_WORD',
    GUESSED_WORD:"GUESSED_WORD",
    ROOM_NOT_AVAILABLE:'ROOM_NOT_AVAILABLE',
    CLUE:'CLUE'
})