name: Staging-Master-branch Build and Deploy
on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CI="" npm run build
     
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P staging --only hosting:staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
